![](figs/se_01.png)
## Workshop Instructions
- <img src="figs/icons/write.svg" width="20" style="filter: invert(41%) sepia(96%) saturate(1449%) hue-rotate(210deg) brightness(100%) contrast(92%);"/> Follow along by typing the code yourself - this helps with learning!
- <img src="figs/icons/code.svg" width="20" style="filter: invert(100%) sepia(100%) saturate(2000%) hue-rotate(40deg) brightness(915%) contrast(100%);"/> Code cells marked as "Exercise" are for you to complete
- <img src="figs/icons/reminder.svg" width="20" style="filter: invert(100%) sepia(100%) saturate(1500%) hue-rotate(30deg) brightness(450%) contrast(70%);"/> Look for hints if you get stuck
- <img src="figs/icons/success.svg" width="20" style="filter: invert(56%) sepia(71%) saturate(5293%) hue-rotate(117deg) brightness(95%) contrast(101%);"/> Compare your solution with the provided answers
- <img src="figs/icons/list.svg" width="20" style="filter: invert(19%) sepia(75%) saturate(6158%) hue-rotate(312deg) brightness(87%) contrast(116%);"/> Don't worry if you make mistakes - debugging is part of learning!

# PyTorch

[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework based on the Torch library.

## Why PyTorch?

PyTorch is a popular starting point for deep learning research due to its flexibility and ease of use, compared to other frameworks like TensorFlow. It is often recommended to use TensorFlow for **production-level projects**, but PyTorch is a great choice for **research and experimentation**. More explicitly, PyTorch has the following advantages:

- **Dynamic computation graph**: PyTorch uses a dynamic computation graph, which means that the graph is generated on-the-fly as operations are created. This is in contrast to TensorFlow, which uses a static computation graph. The dynamic computation graph in PyTorch makes it easier to debug and understand the code.

- **Pythonic**: PyTorch is designed to be Pythonic, which means that it is easy to read and write. This is in contrast to TensorFlow, which uses a more verbose syntax.

- **Imperative programming**: PyTorch uses imperative programming, which means that you can write code that looks like regular Python code. This is in contrast to TensorFlow, which uses declarative programming.

## Setting up the working environment

We are going to use different python modules throughout this course. It is not necessary to be familiar with all of them at the moment. Some of these libraries enable us to work with data and perform numerical operations, while others are used for visualization purposes.

In [1]:
from pathlib import Path
import sys

import utils.core

helper_utils = Path(Path.cwd(), 'utils')
sys.path.append(str(helper_utils))

import utils
import pandas as pd
import torch
import random

checker = utils.core.ExerciseChecker("SE01")

Faculty of Science and Engineering 🔬
The University of Manchester 
Invoking utils version: 0.7.5


# Introduction to tensors
***
<div class="alert alert-block alert-info">
<b>Definition:</b> A tensor is a generalisation of vectors and matrices that can have an arbitrary number of dimensions. In simple terms, a tensor is a multidimensional array.
</div>


Similar to arrays, tensors can have different shapes and sizes. The number of dimensions of a tensor is called its **rank**. Here are some examples of tensors:

- **Scalar**: A scalar is a single number, denoted as a tensor of rank 0.
- **Vector**: A vector is an array of numbers, denoted as a tensor of rank 1.
- **Matrix**: A matrix is a 2D array of numbers, denoted as a tensor of rank 2.
- **3D tensor**: A 3D tensor is a cube of numbers, denoted as a tensor of rank 3.
- **nD tensor**: An nD tensor is a generalisation of the above examples, denoted as a tensor of rank n.

<figure style="background-color: white; border-radius: 10px; padding: 20px; text-align: center; margin: 0 auto;">
    <img src="figs\tensors.png" alt="Visual representation of tensors" align="center" style="width: 60%; height: auto; margin: 0 auto;" />
</figure>


The power of tensors comes in the form of their operations. Tensors can be added, multiplied, and manipulated in various ways.

## Creating tensors
***
To create a tensor in PyTorch, we can use the class `torch.Tensor`. For instance, we can create a scalar tensor using the following code:

<img src="figs/icons/code.svg" width="20" style="filter: invert(100%) sepia(100%) saturate(2000%) hue-rotate(40deg) brightness(915%) contrast(100%);"/> **Snippet 1**: Creating a scalar tensor

```python
x = torch.tensor(101)

# Get the type and shape of the tensor
print(f'x: {x}, type: {type(x)}, shape: {x.shape}')
```

> 📚 **Documentation**: PyTorch is a well documented library, if you struggle with a function, you can always check the [documentation](https://pytorch.org/docs/stable/index.html) for help. You can also use the `help()` function in Python to get more information about a function or class. For example, `help(torch.Tensor)` will give you information about the `Tensor` class.

In [7]:
# Exercise 1: Creating Your First Tensor 🎯
# Try to create:
# 1. A scalar tensor with value 42
# 2. A float tensor with value 3.14

# Your code here:
scalar_tensor = torch.tensor(42) # Add your code
float_tensor = torch.tensor(3.14) # Add your code


# ✅ Check your answer
answer = {
    'scalar_tensor': scalar_tensor,
    'float_tensor': float_tensor
}
checker.check_exercise(1, answer) 

✅ scalar_tensor is correct!
✅ float_tensor is correct!

🎉 Excellent! All parts are correct!


In [8]:
# Check the characteristics of the tensors you created
print(f"Scalar tensor: {scalar_tensor}, type: {type(scalar_tensor)}, shape: {scalar_tensor.shape}, dtype: {scalar_tensor.dtype}")
print(f"Float tensor: {float_tensor}, type: {type(float_tensor)}, shape: {float_tensor.shape}, dtype: {float_tensor.dtype}")

Scalar tensor: 42, type: <class 'torch.Tensor'>, shape: torch.Size([]), dtype: torch.int64
Float tensor: 3.140000104904175, type: <class 'torch.Tensor'>, shape: torch.Size([]), dtype: torch.float32


In the above example, we created a scalar tensor with a single element. Looking at its attributes, we can see that the tensor has a shape of `torch.Size([])`, which means that it has no dimensions. We can also see that the tensor has a data type of `torch.int64`, which means that it is an integer tensor.

<div class="alert alert-block alert-info">
<b>Note:</b> The data type of a tensor is determined by the data type of the elements that it contains. It is important to be aware of the data type of a tensor, as it can affect the results of operations that are performed on it. Good practice is to always specify the data type of a tensor when creating it.
</div>

As we can see our single element is now stored in a type of container, which means that we can perform operations on it but not directly on the element itself. To access the element, we can use the method `item()`.

In [10]:
scalar_tensor, scalar_tensor.item()

(tensor(42), 42)

We can specify the data type of a tensor by passing the `dtype` argument to the `torch.Tensor` constructor. Alternatively, we can use the 'torch.tensor.type` method to change the data type of a tensor.

In [ ]:
# Create a scalar tensor with a specific data type
scalar_tensor = torch.tensor(42, dtype=torch.float32)
print(scalar_tensor)

# Change the data type of a tensor
scalar_tensor = scalar_tensor.type(torch.int64)
print(scalar_tensor)

# Another way to change the data type of a tensor
scalar_tensor = scalar_tensor.int()
print(scalar_tensor)

# # Not recommended as it can be confusing 
# with the .to() method that is used to move tensors
# to different devices
scalar_tensor = scalar_tensor.to(torch.float64) 
print(scalar_tensor) 


tensor(42.)
tensor(42)
tensor(42, dtype=torch.int32)
tensor(42., dtype=torch.float64)


## Initializing tensors
***

PyTorch provides multiple ways to initialize tensors. Here's a comprehensive overview:

| Function | Description | Example | Output Shape |
|----------|-------------|---------|--------------|
| `torch.tensor()` | Creates tensor from data | `torch.tensor([1, 2, 3])` | `(3,)` |
| `torch.zeros()` | Creates tensor of zeros | `torch.zeros(2, 3)` | `(2, 3)` |
| `torch.ones()` | Creates tensor of ones | `torch.ones(2, 3)` | `(2, 3)` |
| `torch.rand()` | Uniform random [0, 1] | `torch.rand(2, 3)` | `(2, 3)` |
| `torch.randn()` | Normal distribution μ=0, σ=1 | `torch.randn(2, 3)` | `(2, 3)` |
| `torch.arange()` | Integer sequence | `torch.arange(5)` | `(5,)` |
| `torch.linspace()` | Evenly spaced sequence | `torch.linspace(0, 1, 5)` | `(5,)` |
| `torch.eye()` | Identity matrix | `torch.eye(3)` | `(3, 3)` |
| `torch.randint()` | Random integers | `torch.randint(0, 10, (2, 3))` | `(2, 3)` |

In [4]:
# Exercise 2: Tensor Initialization 🎯
# Create the following tensors:
# 1. A 3x3 tensor of random integers between 1-10
# 2. A 3x3 identity matrix
# 3. A tensor containing evenly spaced numbers from 0 to 1 (5 numbers)
# 4. A 2x3 tensor of zeros

# Your code here:
random_tensor = torch.randint(1, 10, (3, 3)) # Add your code
identity_matrix = torch.eye(3) # Add your code
spaced_tensor = torch.linspace(0, 1, steps=5) # Add your code
zero_tensor = torch.zeros(2, 3) # Add your code

# ✅ Check your answer
answer = {
    'random_tensor': random_tensor,
    'identity_matrix': identity_matrix,
    'spaced_tensor': spaced_tensor,
    'zero_tensor': zero_tensor
}
checker.check_exercise('2', answer) 

✅ random_tensor is correct!
✅ identity_matrix is correct!
✅ spaced_tensor is correct!
✅ zero_tensor is correct!

🎉 Excellent! All parts are correct!


## Indexing tensors

In order to access the elements of a tensor we can use the same indexing methods used for lists and numpy arrays. We can use the `[]` operator to access the elements of a tensor. 

> **Note:** The indexing is zero-based, which means that the first element has an index of 0.

In [ ]:
myTensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]],
     [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]])


print(f'Element at [0, 1, 2]: {myTensor[0, 1, 2]}')
print(f'Element at [1, 0, 1]: {myTensor[1, 0, 1]}')

Element at [0, 1, 2]: 6
Element at [1, 0, 1]: 11


In [ ]:
# Create a 4x4 tensor for practice
practice_tensor = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Exercise 3: Tensor Indexing 🎯
# Extract the following from practice_tensor:
# 1. The element at position (2,3)
# 2. The second row
# 3. The last column
# 4. The 2x2 submatrix in the bottom right corner
# 5. Every even-numbered element in the first row

# Your code here:
position_2_3 = # Add your code
second_row = # Add your code
last_column = # Add your code
bottom_right = # Add your code
even_elements = # Add your code

# Print results
print(f"Element at (2,3): {position_2_3}")
print(f"Second row: {second_row}")
print(f"Last column: {last_column}")
print(f"Bottom right 2x2:\n{bottom_right}")
print(f"Even elements in first row: {even_elements}")

We can also use the `:` operator to access a range of elements. This is similar to how we access elements in lists and numpy arrays. The `:` operator allows us to specify a range of indices to access a subset of the tensor.

Furthermore, we can use the `...` operator to access all elements in a tensor. This is useful when we want to access all elements in a specific dimension of a tensor. 

Finally, we can use negative indexing to access elements from the end of a tensor. For instance, we can use `-2` to access the second-to-last element of a tensor. 

In [ ]:
# Slicing
print(myTensor[1, 1:3, 1:3])

tensor([[14, 15],
        [17, 18]])


In [ ]:
# Slicing with step
print(myTensor[0, 1:3, 1:3:2])

tensor([[5],
        [8]])


In [ ]:
# Slicing with ellipsis
# Ellipsis (...) can be used to represent multiple colons
print(myTensor[..., 0:2])

tensor([[[ 1,  2],
         [ 4,  5],
         [ 7,  8]],

        [[10, 11],
         [13, 14],
         [16, 17]]])


In [ ]:
# Negative indexing
print(myTensor[..., -1])  # Last element in the last dimension

tensor([[ 3,  6,  9],
        [12, 15, 18]])


# Tensor operations

PyTorch allows us to manipulate tensors in different ways. Since PyTorch is built on top of NumPy, the same operations can be accessed through the `torch` module or alternatively through the `numpy` module. Due to the pythonic nature of PyTorch, we can also use the same operations as we would in Python.

## 🛠️ Basic Operations Cheatsheet
| Operation | Symbol | PyTorch Method | Example |
|-----------|--------|----------------|---------|
| Addition | + | add() | `a + b` |
| Multiplication | * | mul() | `a * b` |
| Matrix Multiply | @ | matmul() | `a @ b` |
| Division | / | div() | `a / b` |

### 💡 Pro Tips
1. **Type Matching**: Ensure tensors have compatible data types
2. **Shape Broadcasting**: Understand how PyTorch broadcasts shapes
3. **GPU Memory**: Be careful with large tensor operations on GPU
4. **Inplace Operations**: Use `_` suffix for inplace operations
   ```python
   # Instead of: x = x + 1
   x.add_(1)  # Inplace addition
   ```

### 🚫 Common Mistakes to Avoid
- Mixing tensor types without conversion
- Forgetting to handle device placement (CPU/GPU)
- Not checking tensor shapes before operations
- Unnecessary copying of large tensors

### 🔍 Debugging Tips
```python
# Quick tensor inspection
print(f"Shape: {tensor.shape}")
print(f"Type: {tensor.dtype}")
print(f"Device: {tensor.device}")
```

In [18]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

In [19]:
# Tensor Addition
c = a + b
print(f'Addition:\n' + '-' * 20)
print(c, '\n')

# Tensor subtraction
c = a - b
print(f'Subtraction:\n' + '-' * 20)
print(c, '\n')

# Tensor multiplication
c = a * b
print(f'Multiplication:\n' + '-' * 20)
print(c, '\n')

# Tensor division
c = a / b
print(f'Division:\n' + '-' * 20)
print(c, '\n')

# Tensor exponentiation
c = a ** b
print(f'Exponentiation:\n' + '-' * 20)
print(c, '\n')

# Tensor square root
c = a ** (1/2)
print(f'Square root:\n' + '-' * 20)
print(c, '\n')

# Tensor logarithm
c = torch.log(a)
print(f'Logarithm:\n' + '-' * 20)
print(c, '\n')


Addition:
--------------------
tensor([[ 6,  8],
        [10, 12]]) 

Subtraction:
--------------------
tensor([[-4, -4],
        [-4, -4]]) 

Multiplication:
--------------------
tensor([[ 5, 12],
        [21, 32]]) 

Division:
--------------------
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]]) 

Exponentiation:
--------------------
tensor([[    1,    64],
        [ 2187, 65536]]) 

Square root:
--------------------
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]]) 

Logarithm:
--------------------
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]]) 



In [ ]:
# Exercise 3: Tensor Operations 🎯
# Create two 2x2 matrices:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Perform the following operations:
# 1. Matrix addition (a + b)
# 2. Element-wise multiplication (a * b)
# 3. Matrix multiplication (a @ b)
# 4. Calculate square root of matrix a

# Your code here:
addition = # Add your code
multiplication = # Add your code
matrix_mult = # Add your code
sqrt_a = # Add your code

# ✅ Check your answer
answer = {
    'addition': addition,
    'multiplication': multiplication,
    'matrix_mult': matrix_mult,
    'sqrt_a': sqrt_a
}
checker.check_exercise(3, answer)

## Matrix operations

Matrix multiplication is a common operation in algebra and is used in many machine learning algorithms. We can perform:

- **Matrix multiplication**: This is the standard matrix multiplication operation, which is denoted by the `@` operator in Python. This operation is also known as the dot product.
- **Element-wise multiplication**: This is the multiplication of two matrices of the same shape, which is denoted by the `*` operator in Python. This operation is also known as the Hadamard product.
- **Matrix transpose**: This is the operation of flipping a matrix over its diagonal, which is denoted by the `.T` attribute in Python. This operation is also known as the matrix transpose.
- **Matrix inverse**: This is the operation of finding the inverse of a matrix, which is denoted by the `torch.inverse()` function in Python. This operation is also known as the matrix inverse.

<figure style="background-color: white; border-radius: 10px; padding: 20px; text-align: center; margin: 0 auto; display: flex; justify-content: center; align-items: center; overflow: hidden;">
    <img src="figs\matrix_mul.gif" alt="Matrix Multiplication" style="width: 40%; height: 220px; object-fit: cover;">
</figure>

In [20]:
# Tensor matrix multiplication
A = torch.ones(3, 3) * 3
B = torch.randint(0, 10, (3, 3)).to(torch.float32)
print(f'Matrix A:\n' + '-' * 20)
print(A, '\n')
print(f'Matrix B:\n' + '-' * 20)
print(B, '\n')

print(f'Matrix multiplication:\n' + '-' * 20)
print(A @ B, '\n')  # Equivalent to A.matmul(B)

print(f'Element-wise multiplication:\n' + '-' * 20)
print(A * B, '\n') # Element-wise multiplication

print(f'Matrix transpose:\n' + '-' * 20)
print(B.T, '\n')  # Transpose of A

Matrix A:
--------------------
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]) 

Matrix B:
--------------------
tensor([[6., 3., 1.],
        [2., 7., 2.],
        [2., 6., 7.]]) 

Matrix multiplication:
--------------------
tensor([[30., 48., 30.],
        [30., 48., 30.],
        [30., 48., 30.]]) 

Element-wise multiplication:
--------------------
tensor([[18.,  9.,  3.],
        [ 6., 21.,  6.],
        [ 6., 18., 21.]]) 

Matrix transpose:
--------------------
tensor([[6., 2., 2.],
        [3., 7., 6.],
        [1., 2., 7.]]) 



## Tensor Broadcasting

Since PyTorch is built on top of NumPy we can use its broadcasting capabilities. Broadcasting is how NumPy handles arrays with different shapes during arithmetic operations. It allows us to perform operations on arrays of different shapes without having to explicitly reshape them. This is done by automatically expanding the smaller array to match the shape of the larger array.

For example, if we have a 1D array of shape `(3,)` and a 2D array of shape `(3, 2)`, we can add them together without having to reshape the 1D array. NumPy will automatically expand the 1D array to match the shape of the 2D array.

> 📚 **Documentation**: [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [21]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5], [6]])

# Broadcasting
c = a + b
print(f'Broadcasting:\n' + '-' * 20)
print(c, '\n')

c = a * b
print(f'Broadcasting with multiplication:\n' + '-' * 20)
print(c, '\n')


Broadcasting:
--------------------
tensor([[ 6,  7],
        [ 9, 10]]) 

Broadcasting with multiplication:
--------------------
tensor([[ 5, 10],
        [18, 24]]) 



## Reshaping tensors
### Unsqueeze
If a tensor is not broadcastable we can use different methods to make it broadcastable. For example, we can use the `unsqueeze` method to add a dimension to the tensor. The `unsqueeze` method takes an integer argument that specifies the dimension to add.

In [22]:
images = torch.rand(8, 3, 32, 32)  #  batch of 8 images, 3 channels (RGB), 32x32 resolution
scaling_factors = torch.tensor([0.5, 1.5, 2.0])  # Shape: (3,)

try:
    scaled_images = images * scaling_factors
except RuntimeError as e:
    print(f'Error: {e}')

# To apply the scaling factors to each channel of the images, we need to unsqueeze the scaling_factors tensor
scaling_factors = scaling_factors.unsqueeze(0).unsqueeze(2).unsqueeze(3)  # Shape: (1, 3, 1, 1)
scaled_images = images * scaling_factors

print(f'Scaled images shape: {scaled_images.shape}')


Error: The size of tensor a (32) must match the size of tensor b (3) at non-singleton dimension 3
Scaled images shape: torch.Size([8, 3, 32, 32])


**Why unsqueeze(0), unsqueeze(2), and unsqueeze(3)?**

When applying channel-specific scaling to images, we need to align the dimensions correctly:

**1. Understanding the Shapes**
- **Images**: `torch.Size([8, 3, 32, 32])`
    - 8 images in the batch
    - 3 channels (RGB)
    - 32×32 pixels per image

- **Scaling Factors**: `torch.Size([3])`
    - One scaling factor per channel

**2. Dimension Transformation**
- **Original**: `[3]` (just channel values)
- **After unsqueeze(0)**: `[1, 3]` (adds batch dimension)
- **After unsqueeze(2)**: `[1, 3, 1]` (adds height dimension)
- **After unsqueeze(3)**: `[1, 3, 1, 1]` (adds width dimension)

**3. Broadcasting in Action**
- The `[1, 3, 1, 1]` tensor broadcasts to `[8, 3, 32, 32]`
- Each scaling factor is applied to its corresponding channel across all images
- Batch dimension (1→8), height (1→32), and width (1→32) dimensions are all broadcast

### View
The `view` method allows us to reshape a tensor while keeping the underlying memory layout. This is useful when we want to change the shape of a tensor without copying the data. The `view` method takes an integer argument that specifies the shape of the tensor after reshaping.

In [23]:
images = torch.rand(8, 3, 32, 32)  #  batch of 8 images, 3 channels (RGB), 32x32 resolution
scaling_factors = torch.tensor([0.5, 1.5, 2.0])  # Shape: (3,)

scaling_factors = scaling_factors.view(1, 3, 1, 1)
scaled_images = images * scaling_factors
print(f'Scaled images shape: {scaled_images.shape}')

Scaled images shape: torch.Size([8, 3, 32, 32])


### Expand
The `expand` method allows us to expand the dimensions of a tensor without copying the data. This is useful when we want to create a tensor with a specific shape without having to copy the data. The `expand` method takes an integer argument that specifies the shape of the tensor after expansion.

In [24]:
a = torch.rand(3,4) # Shape (3, 4)
b = torch.rand(3) # Shape (3,)

try:
    c = a + b
except RuntimeError as e:
    print(f'Error: {e}')

b_expanded = b.unsqueeze(1).expand(3, 4) # Shape (3, 1) -> (3, 4)
c = a + b_expanded
print(f'Expanded b shape: {b_expanded.shape}')
print(f'Final result shape: {c.shape}')

Error: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1
Expanded b shape: torch.Size([3, 4])
Final result shape: torch.Size([3, 4])


## Reshape
The `reshape` method works similarly to the `view` method, but it can also handle cases where the tensor is not contiguous in memory. The latter means that it may create a copy of the data if the memory layout is not compatible. The `reshape` method takes an integer argument that specifies the shape of the tensor after reshaping.

In [25]:
matrix = torch.rand(5, 3)  # Shape: (5, 3)
vector = torch.rand(5)     # Shape: (5,)

# Reshape vector from (5,) to (5,1) to allow broadcasting over (5,3)
vector_reshaped = vector.reshape(5, 1)
result = matrix + vector_reshaped
print(f'Matrix shape: {matrix.shape}')
print(f'Reshaped vector shape: {vector_reshaped.shape}')

Matrix shape: torch.Size([5, 3])
Reshaped vector shape: torch.Size([5, 1])



| Method | Function |
|--------|----------|
| `unsqueeze(dim)` | Adds a singleton dimension at dim |
| `expand(*sizes)` | Expands singleton dimensions without copying data |
| `view(*sizes)` | Reshapes without copying memory (if possible) |
| `reshape(*sizes)` | Reshapes, may create a new memory copy |


# Data to tensors

As mentioned before, PyTorch inherent pythonic nature allows us to easily convert existing data structures to tensors. Thus, we can use different data science libraries to load data and convert it to tensors. We are going to use the `pandas` library to load data from CSV files and convert it to tensors.

In [26]:
data_path = Path(Path.cwd(), 'datasets')
dataset_path = download_dataset('ARKOMA',
                                   dest_path=data_path,
                                   extract=True)

dataset_path = dataset_path / 'Dataset on NAO Robot Arms' / 'Left Arm Dataset' / 'LTrain_x.csv'

NameError: name 'download_dataset' is not defined

DataFrames in pandas are similar to tables in SQL or Excel. They are two-dimensional data structures that can hold different types of data. DataFrames have rows and columns, where each column can have a different data type. We can use the `pandas` library to load data from CSV files and convert it to DataFrames.
> 📚 **Documentation**: [pandas](https://pandas.pydata.org/)

In [ ]:
# Read the dataset
df = pd.read_csv(dataset_path)
df.describe().T

count        mean         std     min       25%      50%       75%  \
Px  6000.0   98.928583   76.226124 -149.87   45.2975  116.345  161.7500   
Py  6000.0  179.584893   52.808400  -30.44  145.8625  180.810  213.7625   
Pz  6000.0   88.939072  124.252501 -117.30  -24.6200   74.065  206.2900   
Rx  6000.0   -4.468263   46.874867 -179.42  -32.7000   -0.910   26.7625   
Ry  6000.0   -1.739148   55.525642 -171.43  -42.1325   -0.305   38.6725   
Rz  6000.0    4.639302   32.807616 -157.10  -13.2125    4.635   23.5825   

       max  
Px  218.63  
Py  315.66  
Pz  318.99  
Rx  159.17  
Ry  166.35  
Rz  153.66

In [ ]:
# Get the data as a numpy array
type(df.Px.values)

numpy.ndarray

In [ ]:
# Convert the numpy array to a PyTorch tensor
px_tensor = torch.tensor(df.Px.values)
px_tensor, px_tensor.shape, px_tensor.ndim, px_tensor.dtype, px_tensor.device

(tensor([-27.9200, 110.5800, 180.9600,  ..., 104.3300, 122.9200, 139.4300],
        dtype=torch.float64),
 torch.Size([6000]),
 1,
 torch.float64,
 device(type='cpu'))

In [ ]:
# Alternatively, we can use the from_numpy method
px_tensor = torch.from_numpy(df.Px.values)
px_tensor, px_tensor.shape, px_tensor.ndim, px_tensor.dtype, px_tensor.device

(tensor([-27.9200, 110.5800, 180.9600,  ..., 104.3300, 122.9200, 139.4300],
        dtype=torch.float64),
 torch.Size([6000]),
 1,
 torch.float64,
 device(type='cpu'))

In [ ]:
# Create a tensor from the entire DataFrame
data = torch.tensor(df.values)
data.shape, data.ndim, data.dtype, data.device

(torch.Size([6000, 6]), 2, torch.float64, device(type='cpu'))

# Using the GPU
PyTorch allows us to use the GPU to accelerate computations. This is done by moving the tensors to the GPU memory. We can do this by using the `to` method of a tensor and passing the device as an argument. The device can be either `cuda` or `cpu`. The `cuda` device refers to the GPU, while the `cpu` device refers to the CPU.

> **Note**: Not all operations are supported on the GPU. If an operation is not supported on the GPU, PyTorch will automatically move the tensor to the CPU and perform the operation there. This can lead to performance issues, so it is important to be aware of which operations are supported on the GPU.

## Checking for GPU availability
We can check if a GPU is available by using the `torch.cuda.is_available()` method. This method returns a boolean value that indicates whether a GPU is available or not. If a GPU is available, we can use it to accelerate computations.

## When to use the GPU
Using the GPU is beneficial when we are working with large tensors or when we are performing operations that are computationally expensive. For example, training a deep learning model on a large dataset can be accelerated by using the GPU. However, if we are working with small tensors or performing simple operations, using the CPU may be faster. 

Typically, we use the GPU for computer vision and natural language processing tasks, where the data is large and the operations are computationally expensive.

> **Note**: When choosing between the CPU and GPU, it is important to make sure that all tensors and models are on the same device. If a tensor is on the CPU and a model is on the GPU, PyTorch will automatically move the tensor to the GPU, which can lead to performance issues. It is important to be aware of which device each tensor and model is on.


In [ ]:
# Check GPU availability
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(f'GPU is available: {device}')
else:
    device = torch.device('cpu')
    print(f'GPU is not available, using CPU: {device}')

# Move the tensor to the GPU
px_tensor = px_tensor.to(device)
print(f'Tensor moved to device: {px_tensor.device}')

GPU is available: cuda


Tensor moved to device: cuda:0
